# Generated by Django 4.2 on 2023-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seiri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='date_task',
            field=models.CharField(help_text='Format: dd-mm-yyyy', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_task',
            field=models.CharField(help_text='Format: dd-mm-yyyy', max_length=10),
        ),
    ]
