# Generated by Django 4.2 on 2023-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seiri', '0002_alter_completedtasks_date_task_alter_task_date_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='date_task',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_task',
            field=models.DateField(),
        ),
    ]
