# Generated by Django 4.0.6 on 2022-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tarefa', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Normal', 'Normal'), ('Baixa', 'Baixa')], max_length=6)),
            ],
        ),
    ]
