# Generated by Django 4.0.6 on 2022-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tarefasconcluidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(),
        ),
    ]
