# Generated by Django 4.0.6 on 2022-09-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_tarefa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefasconcluidas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
