# Generated by Django 4.0.6 on 2022-09-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_tarefasconcluidas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
